### ISSUE TITLE
I have compatibility issues with newer versions Duplicity (v0.7.04/Ubuntu)

### ISSUE THREAD

**Issue by mrtonyhuynh** [alacn1/gdrivebackend#1]
I use Ubuntu with Duplicity 0.7.04.
When using the Backend GDrive, I got the following error:

```
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1523, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1517, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1355, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1103, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 994, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/gdrivebackend.py", line 68, in __init__
    duplicity.backend.Backend.__init__(self, parsed_url)
AttributeError: 'NoneType' object has no attribute 'backend'

Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1523, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1517, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1355, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1095, in ProcessCommandLine
    globals.backend = backend.get_backend(args[0])
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/gdrivebackend.py", line 68, in __init__
    duplicity.backend.Backend.__init__(self, parsed_url)
AttributeError: 'NoneType' object has no attribute 'backend'
```

Hopefully this problem soon be overcome, thank you !

**Comment by alacn1** [comment]
i did split versions in separate files, please try use the duplicity_0.7/gdrivebackend.py and tell me if it works.

**Comment by mrtonyhuynh** [comment]
Wow, thanks! It works like a charm! :smile:
